// // FoodSelection.js
// import React, { useState } from 'react';

// // const PRODUCTS = {
// //   'Б': [
// //     { id: 1, name: 'Творог', mass: 50, unit: 'гр', macro: 'Б', restrictions: [], quantity: 1 },
// //     { id: 2, name: 'Куриная грудка', mass: 30, unit: 'гр', macro: 'Б', restrictions: ['vegetarian'], quantity: 1 },
// //     // Добавьте здесь другие белковые продукты
// //   ],
// //   'М': [
// //     { id: 3, name: 'Кефир', mass: 50, unit: 'гр', macro: 'Б', restrictions: [], quantity: 1 },
// //     { id: 4, name: 'Молоко', mass: 30, unit: 'гр', macro: 'Б', restrictions: ['vegetarian'], quantity: 1 },
// //     // Добавьте здесь другие белковые продукты
// //   ],
// //   'Ф': [
// //     { id: 5, name: 'Арбуз', mass: 50, unit: 'гр', macro: 'Б', restrictions: [], quantity: 1 },
// //     { id: 6, name: 'Дыня', mass: 30, unit: 'гр', macro: 'Б', restrictions: ['vegetarian'], quantity: 1 },
// //     // Добавьте здесь другие белковые продукты
// //   ],
// //   'О': [
// //     { id: 7, name: 'Кефир', mass: 50, unit: 'гр', macro: 'Б', restrictions: [], quantity: 1 },
// //     { id: 8, name: 'Молоко', mass: 30, unit: 'гр', macro: 'Б', restrictions: ['vegetarian'], quantity: 1 },
// //     // Добавьте здесь другие белковые продукты
// //   ],
// //   'К': [
// //     { id: 9, name: 'Булгур крупа', mass: 50, unit: 'гр', macro: 'Б', restrictions: [], quantity: 1 },
// //     { id: 10, name: 'Картофель', mass: 30, unit: 'гр', macro: 'Б', restrictions: ['vegetarian'], quantity: 1 },
// //     // Добавьте здесь другие белковые продукты
// //   ],
// //   'Ж': [
// //     { id: 11, name: 'Авокадо', mass: 50, unit: 'гр', macro: 'Б', restrictions: [], quantity: 1 },
// //     { id: 12, name: 'Оливки', mass: 30, unit: 'гр', macro: 'Б', restrictions: ['vegetarian'], quantity: 1 },
// //     // Добавьте здесь другие белковые продукты
// //   ],
// //   // ... другие группы продуктов
// // };

// const PRODUCTS = {
    
// 'М':[  {'id': 186,
//   'name': 'Сливки 22 %',
//   'mass': '25гр',
//   'unit': 'гр',
//   'ccal': 52,
//   'macro': 'С',
//   'restrictions': ['gluten-free', 'ovo-vegetarian', 'vegan'],
//   'quantity': 1},
//  {'id': 187,
//   'name': 'Сливки кокосовые',
//   'mass': '25гр',
//   'unit': 'гр',
//   'ccal': 54,
//   'macro': 'С',
//   'restrictions': ['gluten-free', 'ovo-vegetarian', 'vegan'],
//   'quantity': 1},
//  {'id': 188,
//   'name': 'Сметана 15%',
//   'mass': '33гр(1,5ст л)',
//   'unit': 'гр',
//   'ccal': 53,
//   'macro': 'С',
//   'restrictions': ['gluten-free', 'ovo-vegetarian', 'vegan'],
//   'quantity': 1},
//  {'id': 189,
//   'name': 'Сыры высокой жирности (в т.ч. Камамбер и Маскарпоне)',
//   'mass': '15гр',
//   'unit': 'гр',
//   'ccal': 54,
//   'macro': 'С',
//   'restrictions': ['gluten-free', 'ovo-vegetarian', 'vegan'],
//   'quantity': 1},
//  {'id': 195,
//   'name': 'Среднее',
//   'mass': 'nan',
//   'unit': 'гр',
//   'ccal': 65,
//   'macro': 'С',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}],
// 'Ф': [{'id': 8,
//   'name': 'Ф фрукты',
//   'mass': 'nan',
//   'unit': 'гр',
//   'ccal': 'nan',
//   'macro': 'Ф',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 37,
//   'name': 'Финики',
//   'mass': '2шт (18гр)',
//   'unit': 'гр',
//   'ccal': 50,
//   'macro': 'Ф',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 73,
//   'name': 'Фасоль стручковая свежая',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 24,
//   'macro': 'Ф',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 115,
//   'name': 'Фасоль (чечевица) отварная',
//   'mass': '50гр',
//   'unit': 'гр',
//   'ccal': 62.2,
//   'macro': 'Ф',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 154,
//   'name': 'Фасоль (чечевица) отварная',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 124,
//   'macro': 'Ф',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}],
// 'А': [{'id': 9,
//   'name': 'Абрикос',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 44,
//   'macro': 'А',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 10,
//   'name': 'Ананас',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 49,
//   'macro': 'А',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 11,
//   'name': 'Арбуз',
//   'mass': '150гр',
//   'unit': 'гр',
//   'ccal': 41,
//   'macro': 'А',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 12,
//   'name': 'Апельсин',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 36,
//   'macro': 'А',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 163,
//   'name': 'Авокадо',
//   'mass': '40гр (1/5 часть)',
//   'unit': 'гр',
//   'ccal': 64.75,
//   'macro': 'А',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}],
// 'Б': [{'id': 13,
//   'name': 'Бананы',
//   'mass': '50',
//   'unit': 'гр',
//   'ccal': 49,
//   'macro': 'Б',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 47,
//   'name': 'Базилик',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 23,
//   'macro': 'Б',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 48,
//   'name': 'Баклажан',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 25,
//   'macro': 'Б',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 79,
//   'name': 'Булгур крупа',
//   'mass': '20гр',
//   'unit': 'гр',
//   'ccal': 68,
//   'macro': 'Б',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 80,
//   'name': 'Булгур приготовленный',
//   'mass': '75гр',
//   'unit': 'гр',
//   'ccal': 69,
//   'macro': 'Б',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 122,
//   'name': 'Б белковые',
//   'mass': 'nan',
//   'unit': 'гр',
//   'ccal': 'nan',
//   'macro': 'Б',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 123,
//   'name': 'Баранина тушеная',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 80,
//   'macro': 'Б',
//   'restrictions': ['ovo-vegetarian',
//    'lacto-vegetarian',
//    'ovo-lacto-vegetarian',
//    'vegan'],
//   'quantity': 1},
//  {'id': 164,
//   'name': 'Баранина тушеная',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 80,
//   'macro': 'Б',
//   'restrictions': ['ovo-vegetarian',
//    'lacto-vegetarian',
//    'ovo-lacto-vegetarian',
//    'vegan'],
//   'quantity': 1}],
// 'В': [{'id': 14,
//   'name': 'Виноград',
//   'mass': '50',
//   'unit': 'гр',
//   'ccal': 36,
//   'macro': 'В',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}],
// 'Г': [{'id': 15,
//   'name': 'Грейпфрут',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 29,
//   'macro': 'Г',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 16,
//   'name': 'Груша',
//   'mass': '100г (1шт)',
//   'unit': 'гр',
//   'ccal': 46,
//   'macro': 'Г',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 17,
//   'name': 'Груша сушеная',
//   'mass': '15гр',
//   'unit': 'гр',
//   'ccal': 41,
//   'macro': 'Г',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 49,
//   'name': 'Горох стручек',
//   'mass': '50гр',
//   'unit': 'гр',
//   'ccal': 28,
//   'macro': 'Г',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 50,
//   'name': 'Грибы шампиньоны',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 27,
//   'macro': 'Г',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 81,
//   'name': 'Горох сухой',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 90,
//   'macro': 'Г',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 82,
//   'name': 'Горох отварной',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 68,
//   'macro': 'Г',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 83,
//   'name': 'Горошек зеленый',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 73,
//   'macro': 'Г',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 84,
//   'name': 'Гречневая крупа ядрица',
//   'mass': '25гр',
//   'unit': 'гр',
//   'ccal': 77,
//   'macro': 'Г',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 85,
//   'name': 'Гречка приготовленная',
//   'mass': '50гр',
//   'unit': 'гр',
//   'ccal': 64,
//   'macro': 'Г',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 124,
//   'name': 'Говядина нежирная (в приготовленном виде)',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 52,
//   'macro': 'Г',
//   'restrictions': ['ovo-vegetarian',
//    'lacto-vegetarian',
//    'ovo-lacto-vegetarian',
//    'vegan'],
//   'quantity': 1},
//  {'id': 125,
//   'name': 'Горох отварной',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 68,
//   'macro': 'Г',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 126,
//   'name': 'Горох сухой',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 90,
//   'macro': 'Г',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}],
// 'Д': [{'id': 18,
//   'name': 'Дыня',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 35,
//   'macro': 'Д',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}],
// 'И': [{'id': 19,
//   'name': 'Изюм',
//   'mass': '15гр (2 ч. ложки)',
//   'unit': 'гр',
//   'ccal': 41,
//   'macro': 'И',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 128,
//   'name': 'Индейка филе (в приготовленном виде)',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 35,
//   'macro': 'И',
//   'restrictions': ['ovo-vegetarian',
//    'lacto-vegetarian',
//    'ovo-lacto-vegetarian',
//    'vegan'],
//   'quantity': 1},
//  {'id': 129,
//   'name': 'Икра красная/черная',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 79,
//   'macro': 'И',
//   'restrictions': ['ovo-vegetarian',
//    'lacto-vegetarian',
//    'ovo-lacto-vegetarian',
//    'vegan'],
//   'quantity': 1},
//  {'id': 165,
//   'name': 'Икра красная/черная',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 79,
//   'macro': 'И',
//   'restrictions': ['ovo-vegetarian',
//    'lacto-vegetarian',
//    'ovo-lacto-vegetarian',
//    'vegan'],
//   'quantity': 1}],
// 'Л': [{'id': 24,
//   'name': 'Лайм',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 30,
//   'macro': 'Л',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 25,
//   'name': 'Лук репчатый ',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 41,
//   'macro': 'Л',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 57,
//   'name': 'Лук порей',
//   'mass': '50гр',
//   'unit': 'гр',
//   'ccal': 17,
//   'macro': 'Л',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 90,
//   'name': 'Лаваш армянский',
//   'mass': '25гр',
//   'unit': 'гр',
//   'ccal': 60,
//   'macro': 'Л',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 91,
//   'name': 'Лапша гречневая "Soba" (в сухом виде)',
//   'mass': '20гр',
//   'unit': 'гр',
//   'ccal': 70,
//   'macro': 'Л',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 92,
//   'name': 'Лапша рисовая (в сухом виде)',
//   'mass': '15гр',
//   'unit': 'гр',
//   'ccal': 52,
//   'macro': 'Л',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 93,
//   'name': 'Лапша Фунчоза (в сухом виде)',
//   'mass': '15гр',
//   'unit': 'гр',
//   'ccal': 48,
//   'macro': 'Л',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 94,
//   'name': 'Лапша яичная (в сухом виде)',
//   'mass': '20гр',
//   'unit': 'гр',
//   'ccal': 77,
//   'macro': 'Л',
//   'restrictions': ['vegan'],
//   'quantity': 1}],
// 'Н': [{'id': 30,
//   'name': 'Нектарин',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 48,
//   'macro': 'Н',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 100,
//   'name': 'Напиток Nemoloko овсяное классическое 3.2%',
//   'mass': '200гр',
//   'unit': 'гр',
//   'ccal': 120,
//   'macro': 'Н',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 101,
//   'name': 'Напиток Nemoloko овсяное классическое лайт 1.5%',
//   'mass': '200гр',
//   'unit': 'гр',
//   'ccal': 90,
//   'macro': 'Н',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 170,
//   'name': 'Напиток Nemoloko овсяное классическое 3.2%',
//   'mass': '200гр',
//   'unit': 'гр',
//   'ccal': 120,
//   'macro': 'Н',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}],
// 'П': [{'id': 31,
//   'name': 'Персик',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 46,
//   'macro': 'П',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 32,
//   'name': 'Помело',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 32,
//   'macro': 'П',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 59,
//   'name': 'Пастернак',
//   'mass': '50гр',
//   'unit': 'гр',
//   'ccal': 24,
//   'macro': 'П',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 60,
//   'name': 'Перец красный',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 39,
//   'macro': 'П',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 104,
//   'name': 'Паста из твердых сортов пшеницы (макароны) в сухом виде ',
//   'mass': '20гр',
//   'unit': 'гр',
//   'ccal': 68,
//   'macro': 'П',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 105,
//   'name': 'Паста из твердых сортов пшеницы (макароны) приготовленные',
//   'mass': '50гр',
//   'unit': 'гр',
//   'ccal': 60.5,
//   'macro': 'П',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 106,
//   'name': 'Пита',
//   'mass': '25гр',
//   'unit': 'гр',
//   'ccal': 60,
//   'macro': 'П',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 107,
//   'name': 'Полба крупа',
//   'mass': '20гр',
//   'unit': 'гр',
//   'ccal': 68,
//   'macro': 'П',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 108,
//   'name': 'Полба приготовленная (на воде)',
//   'mass': '50гр',
//   'unit': 'гр',
//   'ccal': 63,
//   'macro': 'П',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 109,
//   'name': 'Пшенная крупа',
//   'mass': '20гр',
//   'unit': 'гр',
//   'ccal': 68,
//   'macro': 'П',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 135,
//   'name': 'Печень говяжья тушеная',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 38,
//   'macro': 'П',
//   'restrictions': ['ovo-vegetarian',
//    'lacto-vegetarian',
//    'ovo-lacto-vegetarian',
//    'vegan'],
//   'quantity': 1},
//  {'id': 136,
//   'name': 'Печень куриная (сырая)',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 41,
//   'macro': 'П',
//   'restrictions': ['ovo-vegetarian',
//    'lacto-vegetarian',
//    'ovo-lacto-vegetarian',
//    'vegan'],
//   'quantity': 1},
//  {'id': 176,
//   'name': 'Печень трески',
//   'mass': '10гр ',
//   'unit': 'гр',
//   'ccal': 61,
//   'macro': 'П',
//   'restrictions': ['ovo-vegetarian',
//    'lacto-vegetarian',
//    'ovo-lacto-vegetarian',
//    'vegan'],
//   'quantity': 1}],
// 'Т': [{'id': 36,
//   'name': 'Тыква',
//   'mass': '150гр',
//   'unit': 'гр',
//   'ccal': 42,
//   'macro': 'Т',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 69,
//   'name': 'Томаты ',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 18,
//   'macro': 'Т',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 70,
//   'name': 'Томаты Черри',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 15,
//   'macro': 'Т',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 71,
//   'name': 'Томатная паста',
//   'mass': '20гр',
//   'unit': 'гр',
//   'ccal': 20,
//   'macro': 'Т',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 152,
//   'name': 'Творог до 5%',
//   'mass': '50гр',
//   'unit': 'гр',
//   'ccal': 58,
//   'macro': 'Т',
//   'restrictions': ['gluten-free', 'ovo-vegetarian', 'vegan'],
//   'quantity': 1}],
// 'ч': [{'id': 38,
//   'name': 'черешня',
//   'mass': '100',
//   'unit': 'гр',
//   'ccal': 53,
//   'macro': 'ч',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}],
// 'Ч': [{'id': 39,
//   'name': 'Черника',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 44,
//   'macro': 'Ч',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 40,
//   'name': 'Черника свежемороженая',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 51,
//   'macro': 'Ч',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 41,
//   'name': 'Чернослив',
//   'mass': '2шт (15гр)',
//   'unit': 'гр',
//   'ccal': 38,
//   'macro': 'Ч',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 42,
//   'name': 'Чеснок',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 45,
//   'macro': 'Ч',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}],
// 'Я': [{'id': 43,
//   'name': 'Яблоко',
//   'mass': '100г (1шт)',
//   'unit': 'гр',
//   'ccal': 44,
//   'macro': 'Я',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 44,
//   'name': 'Яблоко сушеное',
//   'mass': '15гр',
//   'unit': 'гр',
//   'ccal': 38,
//   'macro': 'Я',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 158,
//   'name': 'Яйцо категории С1',
//   'mass': '1шт',
//   'unit': 'гр',
//   'ccal': 102,
//   'macro': 'Я',
//   'restrictions': ['lacto-vegetarian', 'vegan'],
//   'quantity': 1},
//  {'id': 159,
//   'name': 'Яичный белок',
//   'mass': '1шт',
//   'unit': 'гр',
//   'ccal': 42,
//   'macro': 'Я',
//   'restrictions': ['lacto-vegetarian', 'vegan'],
//   'quantity': 1},
//  {'id': 160,
//   'name': 'Яйцо перепелиное',
//   'mass': '3шт',
//   'unit': 'гр',
//   'ccal': 71,
//   'macro': 'Я',
//   'restrictions': ['lacto-vegetarian', 'vegan'],
//   'quantity': 1},
//  {'id': 193,
//   'name': 'Яйцо категории С1',
//   'mass': '1шт',
//   'unit': 'гр',
//   'ccal': 102,
//   'macro': 'Я',
//   'restrictions': ['lacto-vegetarian', 'vegan'],
//   'quantity': 1},
//  {'id': 194,
//   'name': 'Яйцо перепелиное',
//   'mass': '3шт',
//   'unit': 'гр',
//   'ccal': 71,
//   'macro': 'Я',
//   'restrictions': ['lacto-vegetarian', 'vegan'],
//   'quantity': 1}],
// 'О': [{'id': 46,
//   'name': 'О овощи',
//   'mass': 'nan',
//   'unit': 'гр',
//   'ccal': 'nan',
//   'macro': 'О',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 58,
//   'name': 'Огурец',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 14,
//   'macro': 'О',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 102,
//   'name': 'Овсяные хлопья "Геркулес"',
//   'mass': '20гр',
//   'unit': 'гр',
//   'ccal': 70,
//   'macro': 'О',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 103,
//   'name': 'Овсяная крупа приготовленная',
//   'mass': '75гр',
//   'unit': 'гр',
//   'ccal': 69,
//   'macro': 'О',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 134,
//   'name': 'Осьминог',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 22,
//   'macro': 'О',
//   'restrictions': ['ovo-vegetarian',
//    'lacto-vegetarian',
//    'ovo-lacto-vegetarian',
//    'vegan'],
//   'quantity': 1},
//  {'id': 171,
//   'name': 'Орехи фундук, миндаль',
//   'mass': '8гр (6-8шт)',
//   'unit': 'гр',
//   'ccal': 54.56,
//   'macro': 'О',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 172,
//   'name': 'Орехи грецкие',
//   'mass': '8гр (2шт)',
//   'unit': 'гр',
//   'ccal': 51.84,
//   'macro': 'О',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 173,
//   'name': 'Орехи макадами',
//   'mass': '7гр (2шт)',
//   'unit': 'гр',
//   'ccal': 50,
//   'macro': 'О',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 174,
//   'name': 'Орехи кедровые',
//   'mass': '8гр ',
//   'unit': 'гр',
//   'ccal': 54,
//   'macro': 'О',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 175,
//   'name': 'Оливки',
//   'mass': '30гр (10 шт)',
//   'unit': 'гр',
//   'ccal': 50.4,
//   'macro': 'О',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}],
// 'У': [{'id': 72,
//   'name': 'Укроп',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 40,
//   'macro': 'У',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 153,
//   'name': 'Утка (вареная, тушеная)',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 74,
//   'macro': 'У',
//   'restrictions': ['ovo-vegetarian',
//    'lacto-vegetarian',
//    'ovo-lacto-vegetarian',
//    'vegan'],
//   'quantity': 1},
//  {'id': 190,
//   'name': 'Утка (вареная, тушеная)',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 74,
//   'macro': 'У',
//   'restrictions': ['ovo-vegetarian',
//    'lacto-vegetarian',
//    'ovo-lacto-vegetarian',
//    'vegan'],
//   'quantity': 1}],
// 'Ц': [{'id': 74,
//   'name': 'Цуккини',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 16,
//   'macro': 'Ц',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}],
// 'Ш': [{'id': 75,
//   'name': 'Шпинат',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 22,
//   'macro': 'Ш',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}],
// 'Щ': [{'id': 76,
//   'name': 'Щавель',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 22,
//   'macro': 'Щ',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}],
// 'Х': [{'id': 116,
//   'name': 'Хлеб цельнозерновой',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 80,
//   'macro': 'Х',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 117,
//   'name': 'Хлебцы тонкие зерновые',
//   'mass': '3шт (20гр)',
//   'unit': 'гр',
//   'ccal': 70,
//   'macro': 'Х',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 118,
//   'name': 'Хлопья цельнозерновые (3 ст ложки)',
//   'mass': '20гр',
//   'unit': 'гр',
//   'ccal': 61.400000000000006,
//   'macro': 'Х',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 119,
//   'name': 'Хумус',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 128,
//   'macro': 'Х',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 155,
//   'name': 'Хамон',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 72,
//   'macro': 'Х',
//   'restrictions': ['ovo-vegetarian',
//    'lacto-vegetarian',
//    'ovo-lacto-vegetarian',
//    'vegan'],
//   'quantity': 1},
//  {'id': 156,
//   'name': 'Хумус',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 128,
//   'macro': 'Х',
//   'restrictions': ['vegetarian'],
//   'quantity': 1},
//  {'id': 191,
//   'name': 'Хамон',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 72,
//   'macro': 'Х',
//   'restrictions': ['ovo-vegetarian',
//    'lacto-vegetarian',
//    'ovo-lacto-vegetarian',
//    'vegan'],
//   'quantity': 1},
//  {'id': 192,
//   'name': 'Хумус',
//   'mass': '30гр',
//   'unit': 'гр',
//   'ccal': 128,
//   'macro': 'Х',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}],
// 'Ж': [{'id': 127,
//   'name': 'Желатин пищевой',
//   'mass': '8гр',
//   'unit': 'гр',
//   'ccal': 28,
//   'macro': 'Ж',
//   'restrictions': ['ovo-vegetarian',
//    'lacto-vegetarian',
//    'ovo-lacto-vegetarian',
//    'vegan'],
//   'quantity': 1},
//  {'id': 162,
//   'name': 'Ж жиры',
//   'mass': 'nan',
//   'unit': 'гр',
//   'ccal': 'nan',
//   'macro': 'Ж',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}],
// 'Э': [{'id': 157,
//   'name': 'Эдамаме бобы',
//   'mass': '100гр',
//   'unit': 'гр',
//   'ccal': 80,
//   'macro': 'Э',
//   'restrictions': ['vegetarian'],
//   'quantity': 1}]
// }


// const FoodSelection = ({ userRestrictions, selectedGroup, onSelectionChange }) => {
//   const [selectedProducts, setSelectedProducts] = useState([]);

//   const availableProducts = PRODUCTS[selectedGroup] && userRestrictions
//   ? PRODUCTS[selectedGroup].filter(product =>
//       !userRestrictions.some(restriction => product.restrictions.includes(restriction))
//     )
//   : [];

//   const handleProductSelect = (product) => {
//     setSelectedProducts(prev => {
//       const existing = prev.find(p => p.id === product.id);
//       if (existing) {
//         return prev.map(p => (p.id === product.id ? { ...p, quantity: p.quantity + 1 } : p));
//       } else {
//         return [...prev, product];
//       }
//     });
//     onSelectionChange(selectedProducts);
//   };

//   const handleProductQuantityChange = (id, delta) => {
//     setSelectedProducts(prev => prev.map(p => (p.id === id ? { ...p, quantity: Math.max(1, p.quantity + delta) } : p)));
//     onSelectionChange(selectedProducts);
//   };

//   const handleProductRemove = (id) => {
//     setSelectedProducts(prev => prev.filter(p => p.id !== id));
//     onSelectionChange(selectedProducts);
//   };

//   return (
//     <div>
//       <p>Выберите продукт:</p>
//       {availableProducts.map((product) => (
//         <div key={product.id}>
//           <button onClick={() => handleProductSelect(product)}>{product.name}</button>
//         </div>
//       ))}
//       {selectedProducts.map((product) => (
//         <div key={product.id}>
//           <span>{product.name} {product.mass * product.quantity}{product.unit} – {product.macro}{product.quantity}</span>
//           <button onClick={() => handleProductQuantityChange(product.id, 1)}>+</button>
//           <button onClick={() => handleProductQuantityChange(product.id, -1)}>-</button>
//           <button onClick={() => handleProductRemove(product.id)}>Удалить</button>
//         </div>
//       ))}
//     </div>
//   );
// };

// export default FoodSelection;



import React, { useState, useEffect } from 'react';

const FoodSelection = ({ userRestrictions, selectedGroup, onSelectionChange, PRODUCTS }) => {

  
  const [selectedProducts, setSelectedProducts] = useState([]);

  // Filter available products based on selectedGroup and userRestrictions
  const availableProducts = PRODUCTS[selectedGroup]?.filter(product =>
    !userRestrictions.some(restriction => product.restrictions.includes(restriction))
  ) || [];

  // Update the selection in the parent component whenever selectedProducts changes
  useEffect(() => {
    onSelectionChange(selectedProducts);
  }, [selectedProducts, onSelectionChange]);

  const handleProductSelect = (product) => {
    setSelectedProducts(prev => {
      const existingProduct = prev.find(p => p.id === product.id);
      return existingProduct
        ? prev.map(p => p.id === product.id ? { ...p, quantity: p.quantity + 1 } : p)
        : [...prev, { ...product, quantity: 1 }]; // Set initial quantity to 1
    });
  };

  const handleProductQuantityChange = (id, delta) => {
    setSelectedProducts(prev => prev.map(p =>
      p.id === id ? { ...p, quantity: Math.max(1, p.quantity + delta) } : p
    ));
  };

  const handleProductRemove = (id) => {
    setSelectedProducts(prev => prev.filter(p => p.id !== id));
  };

  return (
    <div>
      <p>Выберите продукт:</p>
      {availableProducts.map((product) => (
        <div key={product.id}>
          <button onClick={() => handleProductSelect(product)}>{product.name}</button>
        </div>
      ))}
      <h3>Ваш выбор:</h3>
      {selectedProducts.map((product) => (
        <div key={product.id}>
          <span>{product.name} ({product.mass * product.quantity}{product.unit}) - {product.macro}{product.quantity}</span>
          <button onClick={() => handleProductQuantityChange(product.id, 1)}>+</button>
          <button onClick={() => handleProductQuantityChange(product.id, -1)}>-</button>
          <button onClick={() => handleProductRemove(product.id)}>Удалить</button>
        </div>
      ))}
    </div>
  );
};

export default FoodSelection;
